version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 99
    assignees:
      - 93V
    ignore:
      - dependency-name: serverless
        versions:
          - ">= 2.a, < 3"
      - dependency-name: "@types/node"
        versions:
          - 14.14.23
          - 14.14.24
          - 14.14.25
          - 14.14.26
          - 14.14.27
          - 14.14.28
          - 14.14.29
          - 14.14.30
          - 14.14.31
          - 14.14.32
          - 14.14.33
          - 14.14.34
          - 14.14.35
          - 14.14.36
          - 14.14.37
          - 14.14.39
          - 14.14.41
          - 15.0.0
      - dependency-name: "@types/jest"
        versions:
          - 26.0.21
          - 26.0.22
          - 26.0.23
      - dependency-name: eslint
        versions:
          - 7.19.0
          - 7.20.0
          - 7.21.0
          - 7.22.0
          - 7.23.0
          - 7.24.0
          - 7.25.0
      - dependency-name: ts-jest
        versions:
          - 26.5.0
          - 26.5.1
          - 26.5.2
          - 26.5.3
          - 26.5.4
          - 26.5.5
      - dependency-name: ssri
        versions:
          - 6.0.2
      - dependency-name: eslint-plugin-prettier
        versions:
          - 3.4.0
      - dependency-name: eslint-config-prettier
        versions:
          - 7.2.0
          - 8.0.0
          - 8.1.0
          - 8.2.0
      - dependency-name: "@typescript-eslint/eslint-plugin"
        versions:
          - 4.14.2
          - 4.15.0
          - 4.15.1
          - 4.15.2
          - 4.16.0
          - 4.16.1
          - 4.17.0
          - 4.18.0
          - 4.19.0
          - 4.20.0
          - 4.21.0
          - 4.22.0
      - dependency-name: "@typescript-eslint/parser"
        versions:
          - 4.14.2
          - 4.15.0
          - 4.15.1
          - 4.15.2
          - 4.16.0
          - 4.16.1
          - 4.17.0
          - 4.18.0
          - 4.19.0
          - 4.20.0
          - 4.21.0
          - 4.22.0
      - dependency-name: "@supercharge/promise-pool"
        versions:
          - 1.6.1
          - 1.6.2
          - 1.7.0
      - dependency-name: typescript
        versions:
          - 4.1.4
          - 4.1.5
          - 4.2.2
          - 4.2.3
          - 4.2.4
      - dependency-name: "@commitlint/cli"
        versions:
          - 12.0.0
          - 12.0.1
          - 12.1.0
      - dependency-name: "@commitlint/config-conventional"
        versions:
          - 12.0.0
          - 12.0.1
          - 12.1.0
      - dependency-name: y18n
        versions:
          - 4.0.1
      - dependency-name: serverless
        versions:
          - 1.83.3
      - dependency-name: husky
        versions:
          - 5.0.9
          - 5.1.0
          - 5.1.1
          - 5.1.2
          - 5.1.3
          - 5.2.0
      - dependency-name: node-notifier
        versions:
          - 8.0.1
          - 8.0.2
      - dependency-name: semantic-release
        versions:
          - 17.3.8
          - 17.3.9
          - 17.4.0
          - 17.4.1
          - 17.4.2
      - dependency-name: "@types/serverless"
        versions:
          - 1.78.13
          - 1.78.21
